=== ScreamBun/jadn-xml-util/_data/rules_criteria_split/rules.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://rulesurl.com/now"
	xmlns="http://rulesurl.com/now"
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:oscal="http://example.org/oscal">

	<!-- <xsd:include schemaLocation="test_criteria.xsd"/> -->
	<xsd:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/xinclude.xsd"/>
	<xsd:import namespace="http://example.org/oscal" schemaLocation="oscal_types.xsd" />
	
	<xsd:complexType name="Rules">
		<xsd:sequence>
			<xsd:element id="rules_rule" name="Rule" type="Rule" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Rule">
		<xsd:sequence>
			<xsd:element id="rule_title" name="title" type="oscal:StringDatatype" minOccurs="1" maxOccurs="1" />
			<xsd:element id="rule_description" name="description" type="oscal:StringDatatype" minOccurs="0" />
			<xsd:element id="rule_tests" name="tests" type="Tests" minOccurs="0" />
			<xsd:element id="rule_logic_statement" name="logic_statement" type="LogicalGroup" />
		</xsd:sequence>
		<xsd:attribute id="rule_uuid" name="uuid" type="oscal:UUIDDatatype" use="required"></xsd:attribute>
		<xsd:attribute id="rule_name" name="name" type="oscal:StringDatatype" use="required"></xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="LogicalGroup">
		<xsd:sequence>
			<xsd:element id="logical_group_component" name="LogicalComponent" type="LogicalComponent" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="LogicalComponent">
		<xsd:choice>
			<xsd:element id="logical_component_test" name="test" type="TestName" />
			<xsd:element id="logical_component_test_group" name="testGroup" type="LogicalGroup" />
			<xsd:element id="logical_component_boolean_logical_operator" name="booleanLogicalOperator" type="BooleanLogicalOperator" />
			<xsd:element id="logical_component_conditional_logical_operator" name="conditionalLogicalOperator" type="ConditionalLogicalOperator" />
		</xsd:choice>
	</xsd:complexType>
	<xsd:simpleType name="BooleanLogicalOperator">
		<xsd:restriction base="oscal:StringDatatype">
			<xsd:enumeration id="boolean_logical_operator_el_1" value="AND">
				<xsd:annotation>
					<xsd:documentation>Logical AND</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration id="boolean_logical_operator_el_2" value="OR">
				<xsd:annotation>
					<xsd:documentation>Logical OR</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration id="boolean_logical_operator_el__3" value="NOT">
				<xsd:annotation>
					<xsd:documentation>Logical NOT</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration id="boolean_logical_operator_el__4" value="XOR">
				<xsd:annotation>
					<xsd:documentation>Logical XOR (Exclusive OR)</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ConditionalLogicalOperator">
		<xsd:restriction base="oscal:StringDatatype">
			<xsd:enumeration id="conditional_logical_operator_el_1" value="AND">
				<xsd:annotation>
					<xsd:documentation>Conditional AND</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration id="conditional_logical_operator_el_2" value="OR">
				<xsd:annotation>
					<xsd:documentation>Conditional OR</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Measurement">
		<xsd:sequence>
			<xsd:element id="measurement_description" name="description" type="oscal:StringDatatype" minOccurs="0" />
			<xsd:element id="measurement_type" name="measurementType" type="MeasurementType" minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute id="measurement_id" name="measurementID" type="oscal:UUIDDatatype" use="required"></xsd:attribute>
		<xsd:attribute id="measurement_name" name="measurementName" type="MeasurementName" use="required"></xsd:attribute>		
	</xsd:complexType>
	<xsd:complexType name="Tests">
		<xsd:sequence>
			<xsd:element id="tests" name="Test" type="Test" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>	
	<xsd:complexType name="Test">
		<xsd:sequence>
			<xsd:element id="test_description" name="testDescription" type="oscal:StringDatatype" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element id="test_measurement" name="measurement" type="Measurement" />
			<xsd:element id="test_criteria_include" ref="xi:include" minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute id="test_id" name="testID" type="oscal:UUIDDatatype" use="required"></xsd:attribute>
		<xsd:attribute id="test_name" name="testName" type="TestName" use="required"></xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="MeasurementType">
		<xsd:choice>
			<xsd:element id="measurement_type_string" name="string" type="oscal:StringDatatype" />
			<xsd:element id="measurement_type_array" name="stringArray" type="oscal:StringDatatype" />
			<xsd:element id="measurement_type_int" name="integer" type="xsd:integer" />
		</xsd:choice>
	</xsd:complexType>
	<xsd:simpleType name="TestName">
		<xsd:restriction base="oscal:StringDatatype" />
	</xsd:simpleType>
	<xsd:simpleType name="MeasurementName">
		<xsd:restriction base="oscal:StringDatatype" />
	</xsd:simpleType>
	<xsd:element id="Rules" name="Rules" type="Rules" />
	
</xsd:schema>

=== ScreamBun/jadn-xml-util/_data/rules_criteria_split/rules.xml
<?xml version="1.0" encoding="UTF-8"?>

<ns:Rules 
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ns="http://rulesurl.com/now"
    xsi:schemaLocation="http://rulesurl.com/now rules.xsd">

    <Rule uuid="64738ff5-5367-5958-9aee-98fffdcd1871" name="TireRule">
        <title>TireRule</title> 
        <tests>
            <Test testID="64738ff5-5367-5958-9aee-98fffdcd1872" testName="urn:niftydemo:test:SC13-pressure">
                <measurement measurementID="64738ff5-5367-5958-9aee-98fffdcd1873" measurementName="urn:niftydemo:test:measurement:SC13-pressure"></measurement> 
                <xi:include href="criteria_tire.xml" xpointer="element('bf90c9c6-370d-4c8d-b9ef-134a624decf5')" parse="xml"/>
            </Test>
            <Test testID="64738ff5-5367-5958-9aee-98fffdcd1874" testName="urn:niftydemo:test:SC13-temp">
                <measurement measurementID="64738ff5-5367-5958-9aee-98fffdcd1873" measurementName="urn:niftydemo:test:measurement:SC13-temp"></measurement> 
                <xi:include href="criteria_tire.xml" xpointer="element('bf90c9c6-370d-4c8d-b9ef-134a624decf6')" parse="xml"/>
            </Test>            
        </tests>
        <logic_statement>
            <LogicalComponent><test>urn:niftydemo:test:SC13-pressure</test></LogicalComponent>
            <LogicalComponent><booleanLogicalOperator>AND</booleanLogicalOperator></LogicalComponent>
            <LogicalComponent><test>urn:niftydemo:test:SC13-temp</test></LogicalComponent>
        </logic_statement>          
    </Rule>  

    <Rule uuid="1b3827ac-1447-407e-a832-fa5bc6b9452c" name="FirewallAllowedRule">
        <title>FirewallAllowedRule</title> 
        <tests>
            <Test testID="4455d7c0-bdcd-41fa-aebc-3c6e83bcc35a" testName="urn:niftydemo:test:SC33-firewallSchemesAllowed">
                <measurement measurementID="42a3f257-6d0e-4996-9be3-24d2ff5bde9c" measurementName="urn:niftydemo:test:measurement:SC33-firewallSchemesAllowed"></measurement> 
                <xi:include href="criteria_firewall.xml" xpointer="element('055634e0-3b88-4d45-b091-948378cf3ae3')" parse="xml"/>
            </Test>
            <Test testID="4455d7c0-bdcd-41fa-aebc-3c6e83bcc35a" testName="urn:niftydemo:test:SC34-firewallDomainsAllowed">
                <measurement measurementID="42a3f257-6d0e-4996-9be3-24d2ff5bde4d" measurementName="urn:niftydemo:test:measurement:SC34-firewallDomainsAllowed"></measurement> 
                <xi:include href="criteria_firewall.xml" xpointer="element('77fda064-4121-420d-a4a6-018a27802d40')" parse="xml"/>
            </Test>           
        </tests>
        <logic_statement>
            <LogicalComponent><test>urn:niftydemo:test:SC33-firewallSchemesAllowed</test></LogicalComponent>
            <LogicalComponent><booleanLogicalOperator>AND</booleanLogicalOperator></LogicalComponent>
            <LogicalComponent><test>urn:niftydemo:test:measurement:SC34-firewallDomainsAllowed</test></LogicalComponent>
        </logic_statement>          
    </Rule>

    <Rule uuid="fe9afc85-7c3d-4dbe-833c-0f049d508ef9" name="FirewallAllowedRule">
        <title>FirewallAllowedRule</title> 
        <tests>
            <Test testID="9e832b8d-3832-41d6-acd9-7a4ddf5113b0" testName="urn:niftydemo:test:SC35-firewallSchemesNotAllowed">
                <measurement measurementID="524cf70f-886f-4e4c-b4ee-7bede3c6e2e4" measurementName="urn:niftydemo:test:measurement:SC35-firewallSchemesNotAllowed"></measurement> 
                <xi:include href="criteria_firewall.xml" xpointer="element('68e72b79-d22c-4951-93a9-c912aef7ad62')" parse="xml"/>
            </Test>
            <Test testID="4a1a4541-7af5-49bd-ac19-1e0d08605868" testName="urn:niftydemo:test:SC36-firewallDomainsNotAllowed">
                <measurement measurementID="352e25bb-e48f-4ece-9471-ee1cce1ba201" measurementName="urn:niftydemo:test:measurement:SC36-firewallDomainsNotAllowed"></measurement> 
                <xi:include href="criteria_firewall.xml" xpointer="element('3c080904-87c6-40cf-bde5-ec2b73c98958')" parse="xml"/>
            </Test>           
        </tests>
        <logic_statement>
            <LogicalComponent><test>urn:niftydemo:test:SC35-firewallSchemesNotAllowed</test></LogicalComponent>
            <LogicalComponent><booleanLogicalOperator>NOT</booleanLogicalOperator></LogicalComponent>
            <LogicalComponent><test>urn:niftydemo:test:SC36-firewallDomainsNotAllowed</test></LogicalComponent>
            <LogicalComponent><booleanLogicalOperator>NOT</booleanLogicalOperator></LogicalComponent>
        </logic_statement>          
    </Rule>    

    <!--xpointer element ref: https://www.w3.org/TR/2003/REC-xptr-element-20030325/ -->

</ns:Rules>
