=== ScreamBun/jadn-xml-util/_data/oscal_rules/test_criteria_2024-01-10.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://example.org/rules"
	xmlns="http://example.org/rules"
	xmlns:oscal="http://example.org/oscal">

	<!--Timestamp: 12 Jan 2024 10:30:15-->

	<xsd:import schemaLocation="oscal_types_2024-01-10.xsd" namespace="http://example.org/oscal" />

	<xsd:complexType name="CriteriaSet">
		<xsd:sequence>
			<xsd:element name="Criteria" type="Criteria" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Criteria">
		<xsd:sequence>
			<xsd:element id="criteria_el_1" name="description" type="oscal:StringDatatype" minOccurs="0"/>
			<xsd:element id="criteria_el_2" name="criteriaValues" type="CriteriaValues" />
		</xsd:sequence>
		<xsd:attribute id="criteria_at_1" name="criteriaID" type="oscal:StringDatatype" use="required"></xsd:attribute>
		<xsd:attribute id="criteria_at_2" name="criteriaName" type="oscal:StringDatatype" use="required"></xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="CriteriaValues">
		<xsd:sequence>
			<xsd:element id="criteriavalues_el_1" name="CriteriaValue" type="CriteriaValue" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CriteriaValue">
		<xsd:sequence>
			<xsd:element id="criteriavalue_el_1" name="valueName" type="oscal:StringDatatype" minOccurs="1" maxOccurs="1" />
			<xsd:element id="criteriavalue_el_2" name="evalItem" type="EvalItem" minOccurs="1" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="EvalItem">
		<xsd:choice>
			<xsd:element id="evalitem_el_1" name="trueFalse" type="xsd:boolean"/>
			<xsd:element id="evalitem_el_2" name="fixedValue" type="xsd:integer" />
			<xsd:element id="evalitem_el_3" name="valueRange" type="ValueRange" />
			<xsd:element id="evalitem_el_4" name="allowedStrings" type="Allowed" />
			<xsd:element id="evalitem_el_5" name="disallowedStrings" type="Disallowed" />
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="ValueRange">
		<xsd:sequence>
			<xsd:element id="valuerange_el_1" name="min" type="xsd:integer" minOccurs="0" maxOccurs="1" />
			<xsd:element id="valuerange_el_2" name="max" type="xsd:integer" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Allowed">
		<xsd:sequence>
			<xsd:element id="allowed_el_1" name="Allowed-Item" type="oscal:StringDatatype" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Disallowed">
		<xsd:sequence>
			<xsd:element id="disallowed_el_1" name="Disallowed-Item" type="oscal:StringDatatype" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="CriteriaSet" type="CriteriaSet" />
	<xsd:element name="Criteria" type="Criteria" />
</xsd:schema>

=== ScreamBun/jadn-xml-util/_data/oscal_rules/tire_criteria_2024-01-10.xml
<?xml version="1.0" encoding="UTF-8"?>
<CriteriaSet xmlns="http://example.com/rules"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example.com/rules test_criteria_2024-01-10.xsd">

    <!--Timestamp: 12 Jan 2024 10:30:45-->

    <Criteria criteriaID="1704925016376" criteriaName="PassengerCarTireCriteria">
        <description>Passenger Car Tire Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>TP</valueName>
                <evalItem>
                    <valueRange>
                        <min>31</min>
                        <max>51</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>
            <CriteriaValue>
                <valueName>Temp</valueName>
                <evalItem>
                    <valueRange>
                        <min>-15</min>
                        <max>120</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>             
        </criteriaValues>
    </Criteria>

    <Criteria criteriaID="1704925021666" criteriaName="BicycleTireCriteria">
        <description>Bicycle Tire Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>TP</valueName>
                <evalItem>
                    <valueRange>
                        <min>40</min>
                        <max>70</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>
            <CriteriaValue>
                <valueName>Temp</valueName>
                <evalItem>
                    <valueRange>
                        <min>0</min>
                        <max>110</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>            
        </criteriaValues>
    </Criteria>       

</CriteriaSet>

=== ScreamBun/jadn-xml-util/_data/oscal_rules/firewall_criteria_2024-01-10.xml
<?xml version="1.0" encoding="UTF-8"?>
<CriteriaSet xmlns="http://example.com/criteria" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example.com/criteria test_criteria_2024-01-10.xsd" >  
    
	<!--Timestamp: 12 Jan 2024 10:30:15-->       

    <Criteria criteriaID="1704925026488" criteriaName="FireWallCriteria">
        <description>Fire Wall Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>allowedSchemes</valueName>
                <evalItem>
                    <allowedStrings>
                        <Allowed-Item>https</Allowed-Item>
                        <Allowed-Item>sftp</Allowed-Item>
                    </allowedStrings>
                </evalItem>
            </CriteriaValue>
            <CriteriaValue>
                <valueName>allowedDomains</valueName>
                <evalItem>
                    <allowedStrings>
                        <Allowed-Item>google.com</Allowed-Item>
                        <Allowed-Item>aws.com</Allowed-Item>
                        <Allowed-Item>microsoft.com</Allowed-Item>
                        <Allowed-Item>nsa.gov</Allowed-Item>
                    </allowedStrings>
                </evalItem>
            </CriteriaValue>             
        </criteriaValues>
    </Criteria>     

</CriteriaSet>
