=== ScreamBun/jadn-xml-util/_data/rules_criteria_combined/test_criteria.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://example.org/rules"
	xmlns="http://example.org/rules"
	xmlns:oscal="http://example.org/oscal">

	<xsd:import schemaLocation="oscal_types.xsd" namespace="http://example.org/oscal" />

	<xsd:complexType name="CriteriaSet">
		<xsd:sequence>
			<xsd:element id="criteriaset_criteria" name="Criteria" type="Criteria" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Criteria">
		<xsd:sequence>
			<xsd:element id="criteria_description" name="description" type="oscal:StringDatatype" minOccurs="0"/>
			<xsd:element id="criteria_criteriavalues" name="criteriaValues" type="CriteriaValues" />
		</xsd:sequence>
		<xsd:attribute id="criteria_criteriaid" name="criteriaID" type="oscal:UUIDDatatype" use="required"></xsd:attribute>
		<xsd:attribute id="criteria_criterianame" name="criteriaName" type="oscal:StringDatatype" use="required"></xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="CriteriaValues">
		<xsd:sequence>
			<xsd:element id="criteriavalues_criteriavalue" name="CriteriaValue" type="CriteriaValue" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CriteriaValue">
		<xsd:sequence>
			<xsd:element id="criteriavalue_valuename" name="valueName" type="oscal:StringDatatype" minOccurs="1" maxOccurs="1" />
			<xsd:element id="criteriavalue_evalitem" name="evalItem" type="EvalItem" minOccurs="1" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="EvalItem">
		<xsd:choice>
			<xsd:element id="evalitem_truefalse" name="trueFalse" type="xsd:boolean"/>
			<xsd:element id="evalitem_fixedvalue" name="fixedValue" type="xsd:integer" />
			<xsd:element id="evalitem_valuerange" name="valueRange" type="ValueRange" />
			<xsd:element id="evalitem_allowedstrings" name="allowedStrings" type="Allowed" />
			<xsd:element id="evalitem_disallowedstrings" name="disallowedStrings" type="Disallowed" />
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="ValueRange">
		<xsd:sequence>
			<xsd:element id="valuerange_min" name="min" type="xsd:integer" minOccurs="0" maxOccurs="1" />
			<xsd:element id="valuerange_max" name="max" type="xsd:integer" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Allowed">
		<xsd:sequence>
			<xsd:element id="allowed_alloweditem" name="AllowedItem" type="oscal:StringDatatype" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Disallowed">
		<xsd:sequence>
			<xsd:element id="disallowed_disalloweditem" name="DisallowedItem" type="oscal:StringDatatype" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="CriteriaSet" type="CriteriaSet" />
	<xsd:element name="Criteria" type="Criteria" />
</xsd:schema>

=== ScreamBun/jadn-xml-util/_data/rules_criteria_combined/tire_criteria.xml
<?xml version="1.0" encoding="UTF-8"?>
<criteria:CriteriaSet xmlns:criteria="http://example.org/rules"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example.org/rules test_criteria.xsd">

    <Criteria criteriaID="bf90c9c6-370d-4c8d-b9ef-134a624decf5" criteriaName="PassengerCarTireCriteria">
        <description>Passenger Car Tire Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>TP</valueName>
                <evalItem>
                    <valueRange>
                        <min>31</min>
                        <max>51</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>
            <CriteriaValue>
                <valueName>Temp</valueName>
                <evalItem>
                    <valueRange>
                        <min>-15</min>
                        <max>120</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>             
        </criteriaValues>
    </Criteria>
    <Criteria criteriaID="deaa7a67-1fa0-46a8-8d47-45acea9ec219" criteriaName="BicycleTireCriteria">
        <description>Bicycle Tire Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>TP</valueName>
                <evalItem>
                    <valueRange>
                        <min>40</min>
                        <max>70</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>
            <CriteriaValue>
                <valueName>Temp</valueName>
                <evalItem>
                    <valueRange>
                        <min>0</min>
                        <max>110</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>            
        </criteriaValues>
    </Criteria>    

</criteria:CriteriaSet>

=== ScreamBun/jadn-xml-util/_data/rules_criteria_split/criteria_tire.xml
<?xml version="1.0" encoding="UTF-8"?>
<criteria:CriteriaSet 
    xmlns:xi="http://www.w3.org/2001/XInclude" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:criteria="http://rulesurl.com/now"
    xsi:schemaLocation="http://rulesurl.com/now test_criteria.xsd">

    <Criteria xmlns:ns="http://rulesurl.com/now" criteriaID="bf90c9c6-370d-4c8d-b9ef-134a624decf5" criteriaName="PassengerCarTirePressureCriteria">
        <description>Passenger Car Tire Pressure Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>TP</valueName>
                <evalItem>
                    <valueRange>
                        <min>31</min>
                        <max>50</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>           
        </criteriaValues>
    </Criteria>

    <Criteria xmlns:ns="http://rulesurl.com/now" criteriaID="bf90c9c6-370d-4c8d-b9ef-134a624decf6" criteriaName="PassengerCarTireTempCriteria">
        <description>Passenger Car Tire Temp Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>Temp</valueName>
                <evalItem>
                    <valueRange>
                        <min>-15</min>
                        <max>120</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>             
        </criteriaValues>
    </Criteria>      

</criteria:CriteriaSet>

=== ScreamBun/jadn-xml-util/_data/rules_criteria_split/criteria_firewall.xml
<?xml version="1.0" encoding="utf-8"?>
<criteria:CriteriaSet 
    xmlns:xi="http://www.w3.org/2001/XInclude" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:criteria="http://rulesurl.com/now"
    xsi:schemaLocation="http://rulesurl.com/now test_criteria.xsd">

    <Criteria criteriaID="055634e0-3b88-4d45-b091-948378cf3ae3" criteriaName="FirewallSchemesAllowedCriteria">
        <description>Firewall Schemes Allowed Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>allowedSchemes</valueName>
                <evalItem>
                    <allowedStrings>
                        <AllowedItem>https</AllowedItem>
                        <AllowedItem>sftp</AllowedItem>
                    </allowedStrings>
                </evalItem>
            </CriteriaValue>           
        </criteriaValues>
    </Criteria>   

    <Criteria criteriaID="68e72b79-d22c-4951-93a9-c912aef7ad62" criteriaName="FirewallSchemesNotAllowedCriteria">
        <description>Firewall Schemes Not Allowed Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>notAllowedSchemes</valueName>
                <evalItem>
                    <allowedStrings>
                        <AllowedItem>http</AllowedItem>
                        <AllowedItem>ftp</AllowedItem>
                    </allowedStrings>
                </evalItem>
            </CriteriaValue>           
        </criteriaValues>
    </Criteria>     

    <Criteria criteriaID="77fda064-4121-420d-a4a6-018a27802d40" criteriaName="FirewallDomainsAllowedCriteria">
        <description>Firewall Domains Allowed Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>allowedDomains</valueName>
                <evalItem>
                    <allowedStrings>
                        <AllowedItem>google.com</AllowedItem>
                        <AllowedItem>aws.com</AllowedItem>
                        <AllowedItem>microsoft.com</AllowedItem>
                        <AllowedItem>nsa.gov</AllowedItem>
                    </allowedStrings>
                </evalItem>
            </CriteriaValue>             
        </criteriaValues>
    </Criteria>     

    <Criteria criteriaID="3c080904-87c6-40cf-bde5-ec2b73c98958" criteriaName="FirewallDomainsNotAllowedCriteria">
        <description>Firewall Domains Not Allowed Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>notAllowedDomains</valueName>
                <evalItem>
                    <allowedStrings>
                        <AllowedItem>aol.com</AllowedItem>
                        <AllowedItem>yahoo.com</AllowedItem>
                        <AllowedItem>texasholdem.com</AllowedItem>
                        <AllowedItem>mgm.com</AllowedItem>
                    </allowedStrings>
                </evalItem>
            </CriteriaValue>             
        </criteriaValues>
    </Criteria>     

</criteria:CriteriaSet>

=== ScreamBun/jadn-xml-util/_data/rules_criteria_combined/firewall_criteria.xml
<?xml version="1.0" encoding="utf-8"?>
<criteria:CriteriaSet xmlns:criteria="http://example.org/rules"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example.org/rules test_criteria.xsd">

    <Criteria criteriaID="21c515b8-1db0-442c-a51d-5cc1430c9818" criteriaName="FireWallCriteria">
        <description>Fire Wall Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>allowedSchemes</valueName>
                <evalItem>
                    <allowedStrings>
                        <AllowedItem>https</AllowedItem>
                        <AllowedItem>sftp</AllowedItem>
                    </allowedStrings>
                </evalItem>
            </CriteriaValue>
            <CriteriaValue>
                <valueName>allowedDomains</valueName>
                <evalItem>
                    <allowedStrings>
                        <AllowedItem>google.com</AllowedItem>
                        <AllowedItem>aws.com</AllowedItem>
                        <AllowedItem>microsoft.com</AllowedItem>
                        <AllowedItem>nsa.gov</AllowedItem>
                    </allowedStrings>
                </evalItem>
            </CriteriaValue>             
        </criteriaValues>
    </Criteria>   

</criteria:CriteriaSet>

=== ScreamBun/jadn-xml-util/_data/rules_criteria_split/criteria_tire_pressure.xml
<?xml version="1.0" encoding="UTF-8"?>
<criteria:CriteriaSet 
    xmlns:xi="http://www.w3.org/2001/XInclude" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:criteria="http://rulesurl.com/now"
    xsi:schemaLocation="http://rulesurl.com/now test_criteria.xsd">

    <Criteria xmlns:ns="http://rulesurl.com/now" criteriaID="bf90c9c6-370d-4c8d-b9ef-134a624decf5" criteriaName="PassengerCarTireCriteria">
        <description>Passenger Car Tire Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>TP</valueName>
                <evalItem>
                    <valueRange>
                        <min>31</min>
                        <max>51</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>
            <CriteriaValue>
                <valueName>Temp</valueName>
                <evalItem>
                    <valueRange>
                        <min>-15</min>
                        <max>120</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>             
        </criteriaValues>
    </Criteria>

    <Criteria xmlns:ns="http://rulesurl.com/now" criteriaID="bf90c9c6-370d-4c8d-b9ef-134a624decf6" criteriaName="TruckCarTireCriteria">
        <description>Truck Tire Criteria</description>
        <criteriaValues>
            <CriteriaValue>
                <valueName>TP</valueName>
                <evalItem>
                    <valueRange>
                        <min>32</min>
                        <max>55</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>
            <CriteriaValue>
                <valueName>Temp</valueName>
                <evalItem>
                    <valueRange>
                        <min>-25</min>
                        <max>125</max>
                    </valueRange>
                </evalItem>
            </CriteriaValue>             
        </criteriaValues>
    </Criteria>    

</criteria:CriteriaSet>
